/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
*/

const expect = require('expect');

describe('389 Find the Difference', () => {
  it('returns the difference between two strings', () => {
    //arragne
    const input1 = 'abcdeghijk';
    const input2 = 'kabcjihgedf';
    const expected = 'f';
    //act
    const actual = findTheDifference(input1, input2);
    //assert
    expect(actual).toBe(expected);
  });
});

const findTheDifference = (input1, input2) => {
  return [...input2].filter(input2Val => {
    if (input1.includes(input2Val)) {
      const input1Array = [...input1];
      input1Array.splice(input1Array.indexOf(input2Val), 1);
      input1 = input1Array.join('');
      return false;
    }
    return true;
  })[0];
};
